#!/usr/bin/env node
/**
 * generateFontRequires.js — generates services/mushafFontRequires.ts
 *
 * Must be run AFTER downloadQCFFonts.js has placed all 606 font files in
 * assets/fonts/qcf/. Metro bundler requires static require() calls — they
 * cannot be generated at runtime. This script writes the file with all
 * 606 static requires so Metro can bundle them.
 *
 * Run from the project root:
 *   node scripts/generateFontRequires.js
 *
 * After this script:
 *   1. Verify assets/fonts/qcf/ has all 606 .ttf files
 *   2. In services/mushafFontManager.ts set:
 *      const OFFLINE_MODE: 'bundled' | 'download' = 'bundled';
 *   3. Build and test on simulator/device
 */

const fs   = require('fs');
const path = require('path');

const FONTS_DIR = path.resolve(__dirname, '../assets/fonts/qcf');
const OUT_FILE  = path.resolve(__dirname, '../services/mushafFontRequires.ts');

function main() {
  // Verify all font files exist
  const missing = [];
  for (let n = 1; n <= 604; n++) {
    const file = path.join(FONTS_DIR, `p${String(n).padStart(3, '0')}.ttf`);
    if (!fs.existsSync(file)) missing.push(file);
  }
  for (const name of ['surah_names.ttf', 'bismillah.ttf']) {
    const file = path.join(FONTS_DIR, name);
    if (!fs.existsSync(file)) missing.push(file);
  }

  if (missing.length > 0) {
    console.error(`ERROR: ${missing.length} font file(s) missing from assets/fonts/qcf/`);
    console.error('Run: node scripts/downloadQCFFonts.js first');
    missing.slice(0, 10).forEach(f => console.error(' ', path.basename(f)));
    if (missing.length > 10) console.error(`  ...and ${missing.length - 10} more`);
    process.exit(1);
  }

  // Build page font requires
  const pageLines = [];
  for (let n = 1; n <= 604; n++) {
    const key  = n;
    const file = `p${String(n).padStart(3, '0')}.ttf`;
    pageLines.push(`  ${key}: require('../assets/fonts/qcf/${file}'),`);
  }

  const output = `/**
 * mushafFontRequires.ts — AUTO-GENERATED by scripts/generateFontRequires.js
 *
 * DO NOT EDIT MANUALLY. Re-run the generator script to update.
 *
 * Metro bundler requires static require() calls that cannot be dynamic.
 * This file contains all 606 static requires for bundled offline mode.
 *
 * This file is only used when OFFLINE_MODE = 'bundled' in mushafFontManager.ts.
 * In download mode, these require() calls are never executed, but Metro still
 * resolves them at bundle time — all 606 font files MUST be present in
 * assets/fonts/qcf/ before running 'expo build' or 'eas build'.
 */

// Page fonts — 604 entries
export const PAGE_FONT_REQUIRES: Record<number, number> = {
${pageLines.join('\n')}
};

// Surah name icon font — PostScript name: "icomoon" (nameID 6 confirmed from SVG source)
// eslint-disable-next-line @typescript-eslint/no-var-requires
export const SURAH_NAME_REQUIRE: number = require('../assets/fonts/qcf/surah_names.ttf');

// Bismillah font — PostScript name: "QCF_BSML" (confirmed)
// eslint-disable-next-line @typescript-eslint/no-var-requires
export const BISMILLAH_REQUIRE: number = require('../assets/fonts/qcf/bismillah.ttf');
`;

  fs.writeFileSync(OUT_FILE, output, 'utf8');
  console.log(`\nGenerated: ${OUT_FILE}`);
  console.log(`  ${604} page font requires`);
  console.log('  1 surah_names require');
  console.log('  1 bismillah require');
  console.log('\nNext step: set OFFLINE_MODE = \'bundled\' in services/mushafFontManager.ts\n');
}

main();
